### ISSUE TITLE
Throw ERR_INVALID_ARG_TYPE(name, 'string', value) in win10

### ISSUE THREAD

**Issue by 5468sun** [kristerkari/react-native-css-modules#27]
I use  react-native-less-transformer and less to style my app。
If i import another .less file in .less file, metro will throw Error 。

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   D:\P-Project\dproject

Loading dependency graph, done.
transform[stderr]: internal/validators.js:125
transform[stderr]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
transform[stderr]:     ^
transform[stderr]:
transform[stderr]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
transform[stderr]:     at validateString (internal/validators.js:125:11)
transform[stderr]:     at Object.join (path.js:427:7)
transform[stderr]:     at tryPrefix (D:\P-Project\dproject\node_modules\less\lib\less-node\file-manager.js:76:49)
transform[stderr]:     at tryPathIndex (D:\P-Project\dproject\node_modules\less\lib\less-node\file-manager.js:163:19)
transform[stderr]:     at tryPrefix (D:\P-Project\dproject\node_modules\less\lib\less-node\file-manager.js:161:25)
transform[stderr]:     at ReadFileContext.<anonymous> (D:\P-Project\dproject\node_modules\less\lib\less-node\file-manager.js:148:48)
transform[stderr]:     at ReadFileContext.callback (D:\P-Project\dproject\node_modules\graceful-fs\graceful-fs.js:90:16)transform[stderr]:     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
```

**Comment by kristerkari** [comment]
Thanks @5468sun !

I need to have a look at this. I'm not using Windows, so let's see if I manage to reproduce the issue. Do you have an example of the exact style files that trigger the error?

**Comment by 5468sun** [comment]
@kristerkari  here is the example.
https://github.com/5468sun/aproject
thanks.

**Comment by 5468sun** [comment]
new update. 
I install react native tools for vscode, try to debug.
when i hit Debug Android button to start up the packager. it works fine.

but if i run react-native run-android from vscode‘s default terminal, it still throw the same error.

**Comment by kristerkari** [comment]
I quickly tested your repo, and it's working fine for me on Mac OS. 

Must be something Windows or Node.js specific.

**Comment by 5468sun** [comment]
my repo work fine for me on Mac OS. (both react-native run-android and react-native run-ios.)

i've been searching around. it seems
throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
is a common nodejs error. im giving up develop android app on window.

**Comment by kristerkari** [comment]
Alright, I'll close this issue then :+1:
